config/routes.rb
Rails.application.routes.draw do
  
  resources :sightings
  resources :animals
  
  root to: "animals#index"

end

app/models/animal.rb
class Animal < ApplicationRecord
    
    has_many :sightings
    
    validates :common_name, :latin_name, :kingdom, presence: true
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
    
    belongs_to :animal
    
    validates :date, :time, :latitude, :longitude, :region, presence: true
    
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    
    def index
        @animal = Animal.all
    end
    
    def new
        @animal = Animal.new
    end
    
    def show
        @animal = Animal.find(params[:id])
        
    end
    
    def create
        
        @animal = Animal.new(animal_params)
        
        if @animal.save
            redirect_to animals_path
        else 
            render action: :new
        end
    end
    
    def edit
        @animal = Animal.find(params[:id])

    end
    
    def update
        
         @animal = Animal.find(params[:id])
            
        if @animal.update_attributes(animal_params)
            redirect_to animals_path
            
        else 
            render :edit
        end
    
    end
    
    def destroy
        
         @animal = Animal.destroy(params[:id])
         
         if @animal.destroy
             redirect_to animals_path
         
        else
            render destroy
        end
        
    end
    
end


private 

    def animal_params
            params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
    
    def index
        @sighting = Sighting.all
    end
    
    def new 
        
        animal = Animal.find(params[:animal_id])
        @sighting = animal.sightings.new
        
    end
    
    def create

        @sighting = Sighting.new(sighting_params)
        
        if @sighting.save
            redirect_to animal_path(@sighting.animal)
        else 
            render action: :new
        end
    
    end
    
    def edit
        @sighting = Sighting.find(params[:id])

    end
    
    def update
        
        @sighting = Sighting.find(params[:id])
        
        if @sighting.update_attributes(sighting_params)
            redirect_to animal_path(@sighting.animal)
        else 
            render action: :edit
        end
    
    end
    
        def destroy
        
         @sighting = Sighting.destroy(params[:id])
         
         if @sighting.destroy
             redirect_to animal_path(@sighting.animal)
         
        else
            render action: :destroy
        end
        
    end
    
    
end

private 

    def sighting_params
            params.require(:sighting).permit(:animal_id, :date, :time, :latitude, :longitude, :region)
    end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/edit.html.erb
<h1>Add an animal</h1>

<%= form_for @animal, url: {action: :update} do |e| %>

<%= e.label :name %>
<%= e.text_field :common_name %>

<%= e.label :latin_name %>
<%= e.text_field :latin_name %>

<%= e.label :kingdom %>
<%= e.text_field :kingdom %>

<%= e.submit 'Update' %>



<%end%>

app/views/animals/index.html.erb
<h1>Welcome to the Home Page</h1>



<%= link_to 'Add an Animal', new_animal_path %>

<% @animal.each do | list | %>
    <li> <%=list.common_name %>
    <%= link_to 'More Info', animal_path(list) %>
    <%= link_to 'Update', edit_animal_path(list) %>
    <%= link_to 'Delete', animal_path(list), method: :delete %>
    </li>
    
    
<% end %>

app/views/animals/new.html.erb
<h1>Add an animal</h1>

<%= form_for @animal do |e| %>

<%= e.label :name %>
<%= e.text_field :common_name %>

<%= e.label :latin_name %>
<%= e.text_field :latin_name %>

<%= e.label :kingdom %>
<%= e.text_field :kingdom %>

<%= e.submit %>



<%end%>

app/views/animals/show.html.erb
<h1>
<%= @animal.common_name %>
<%= @animal.latin_name %>
<%= @animal.kingdom %>
</h1>

<ul>

<% @animal.sightings.each do |sighting| %>


    <li>Date : <%= sighting.date %> Time : <%= sighting.time %> Latitude <%= sighting.latitude %> Longitude <%= sighting.longitude %> Region <%= sighting.region %></li>
    <%= link_to "Update", edit_sighting_path(sighting) %>
    <%= link_to "Delete", sighting_path(sighting), method: :delete %>
    
  <% end %>
  
</ul>





<%= link_to "Create Sighting", new_sighting_path({animal_id: @animal.id}) %>

<%= link_to "Go Back Home", animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/edit.html.erb
<h1>Update sighting</h1>

<%= form_for @sighting  do |e| %>

<%= e.hidden_field :animal_id %>

<%= e.label :date %>
<%= e.text_field :date %>

<%= e.label :time %>
<%= e.text_field :time %>

<%= e.label :latitude %>
<%= e.text_field :latitude %>

<%= e.label :longitude %>
<%= e.text_field :longitude %>

<%= e.label :region %>
<%= e.text_field :region %>

<%= e.submit "Update" %>



<%end%>

app/views/sightings/index.html.erb
<h1>Welcome</h1>

app/views/sightings/new.html.erb
<h1>Add an a sighting of an aminal</h1>

<%= form_for @sighting, url: {action: :create} do |e| %>

<%= e.hidden_field :animal_id %>

<%= e.label :date %>
<%= e.text_field :date %>

<%= e.label :time %>
<%= e.text_field :time %>

<%= e.label :latitude %>
<%= e.text_field :latitude %>

<%= e.label :longitude %>
<%= e.text_field :longitude %>

<%= e.label :region %>
<%= e.select :region, [['SD','SD'],['LA','LA'],['SF','SF']] %>

<%= e.submit %>



<%end%>